(() => {
  'use strict';
  const {exercises,validate} = window.JavaPractice;
  const STORAGE_KEY = 'falomir_java_sentencias_2026_27_v1';
  const $ = s => document.querySelector(s);
  const escapeHtml = str => String(str ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function fresh(){return {name:'',code:{},results:{},selected:1};}
  function load(){try {const s=JSON.parse(localStorage.getItem(STORAGE_KEY));return s&&typeof s==='object'?{...fresh(),...s,code:s.code||{},results:s.results||{}}:fresh();}catch{return fresh();}}
  const state=load();
  function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('#saveState').textContent='✓ Guardado local automático';}catch{$('#saveState').textContent='No se puede guardar en este navegador: exporta tu código.';}}
  function resultOf(id){const code=state.code[id]||''; if(!code.trim())return null;return state.results[id]||null;}
  function totalProgress(){const validations=exercises.map(e=>resultOf(e.id));let full=0,passed=0,total=0;validations.forEach((v,i)=>{if(v?.complete)full++;passed+=v?.passed||0;total+=exercises[i].criteria.length;});return {full,passed,total};}
  function showProgress(){const p=totalProgress();$('#progressTotal').textContent=`${p.full} / ${exercises.length}`;$('#progressBar').style.width=`${p.full/exercises.length*100}%`;$('#progressDetail').textContent=`${p.passed} de ${p.total} criterios validados`;$('#finishStatus').textContent=p.full===exercises.length?'Todos los ejercicios constan como superados en la autovalidación formativa.':`Has superado ${p.full} de ${exercises.length} ejercicios; el justificante reflejará los pendientes y los criterios parciales.`;}
  function showNav(){const nav=$('#exerciseNav');nav.innerHTML='';exercises.forEach(e=>{const v=resultOf(e.id);const b=document.createElement('button');b.type='button';b.className='nav-item'+(e.id===state.selected?' active':'')+(v?.complete?' done':v?.passed?' partial':'');b.innerHTML=`<span class="nav-id">${v?.complete?'✓':e.id}</span><span>${escapeHtml(e.title)}</span>`;b.title=`Ejercicio ${e.id}: ${e.title} · ${v?v.passed+'/'+v.total+' criterios':'Pendiente de validar'}`;b.setAttribute('aria-current',e.id===state.selected?'step':'false');b.addEventListener('click',()=>select(e.id));nav.append(b);});}
  function statusHtml(v){if(!v)return ['Pendiente',''];if(v.complete)return ['✓ Superado','ok'];if(v.passed)return [`${v.passed}/${v.total} criterios`,'partial'];return ['Sin criterios superados',''];}
  function select(id){const e=exercises.find(x=>x.id===id);if(!e)return;state.selected=id;save();$('#exerciseNumber').textContent=`Ejercicio ${String(id).padStart(2,'0')} · ${exercises.length}`;$('#exerciseTitle').textContent=e.title;$('#exerciseHeading').textContent=e.groups;$('#exerciseDesc').textContent=e.desc;$('#exerciseHint').textContent=e.hint;$('#exerciseData').hidden=!e.example;$('#exerciseData').textContent=e.example?'REFERENCIA DE RESULTADOS\n'+e.example:'';$('#levelBadge').textContent=e.level;$('#codeEditor').value=state.code[id]??e.template;$('#pagerText').textContent=`${id} de ${exercises.length}`;$('#prevBtn').disabled=id===1;$('#nextBtn').disabled=id===exercises.length;showResult(resultOf(id));showNav();showProgress();}
  function showResult(v){const f=$('#feedback');const badge=$('#exerciseState');const [text,css]=statusHtml(v);badge.textContent=text;badge.className='pill '+css;f.hidden=!v;if(!v)return;f.className='feedback '+(v.complete?'success':v.passed?'partial':'');f.innerHTML=`<h4>${v.complete?'✓ Ejercicio superado en la autovalidación':`Comprobación parcial · ${v.passed} / ${v.total} criterios`}</h4><p class="feedback-summary">${escapeHtml(v.note)}</p><div class="check-list">${v.results.map(r=>`<div class="check-row ${r.pass?'passed':'pending'}"><span class="check-sign">${r.pass?'✓':'○'}</span><span>${escapeHtml(r.label)}</span></div>`).join('')}</div>`;}
  function validateSelected(){const id=state.selected,code=$('#codeEditor').value;state.code[id]=code;if(!code.trim()){alert('Escribe o pega un programa Java antes de validarlo.');return;}const result=validate(id,code);state.results[id]=result;save();showResult(result);showNav();showProgress();$('#feedback').scrollIntoView({behavior:'smooth',block:'nearest'});}
  $('#studentName').value=state.name||'';
  $('#studentName').addEventListener('input',e=>{state.name=e.target.value;save();});
  $('#codeEditor').addEventListener('input',e=>{state.code[state.selected]=e.target.value;delete state.results[state.selected];save();showResult(null);showNav();showProgress();});
  $('#codeEditor').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const el=e.currentTarget,start=el.selectionStart;el.setRangeText('    ',start,el.selectionEnd,'end');el.dispatchEvent(new Event('input',{bubbles:true}));}});
  $('#validateBtn').addEventListener('click',validateSelected);
  $('#prevBtn').addEventListener('click',()=>select(state.selected-1));
  $('#nextBtn').addEventListener('click',()=>select(state.selected+1));
  $('#templateBtn').addEventListener('click',()=>{if(!confirm('¿Restaurar la plantilla de este ejercicio? Tu código actual será sustituido.'))return;const e=exercises[state.selected-1];$('#codeEditor').value=e.template;$('#codeEditor').dispatchEvent(new Event('input',{bubbles:true}));});
  $('#copyBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#codeEditor').value);$('#saveState').textContent='✓ Código copiado';}catch{const editor=$('#codeEditor');editor.focus();editor.select();$('#saveState').textContent='Seleccionado: usa Ctrl+C o ⌘C para copiar.';}});
  $('#resetBtn').addEventListener('click',()=>{if(!confirm('Se borrarán todos tus códigos, validaciones y nombre guardados en este navegador. ¿Continuar?'))return;try{localStorage.removeItem(STORAGE_KEY);}catch{}location.reload();});
  function snapshot(){// Recalcula SIEMPRE todos los criterios al generar el documento: nunca confía en resultados obsoletos.
    const entries=exercises.map(e=>({id:e.id,title:e.title,group:e.groups,code:state.code[e.id]||'',validation:(state.code[e.id]||'').trim()?validate(e.id,state.code[e.id]):null}));
    const done=entries.filter(x=>x.validation?.complete).length,passed=entries.reduce((n,x)=>n+(x.validation?.passed||0),0),total=exercises.reduce((n,e)=>n+e.criteria.length,0);
    return {name:state.name.trim(),when:new Date(),entries,done,passed,total};
  }
  function shortFingerprint(input){let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).toUpperCase().padStart(8,'0');}
  let lastReceipt=null;
  function receiptMarkup(r){const date=r.when.toLocaleString('es-ES',{dateStyle:'long',timeStyle:'short'});const code='JAVA-'+shortFingerprint([r.name,r.when.toISOString(),...r.entries.map(x=>x.code)].join('|'));
    const rows=r.entries.map(x=>{const v=x.validation,part=v?`${v.passed}/${v.total}`:'0/'+exercises[x.id-1].criteria.length,status=v?.complete?'Superado':v?.passed?'Parcial':'Pendiente',cls=v?.complete?'done':v?.passed?'partial':'pending';return `<tr><td>${x.id}</td><td>${escapeHtml(x.title)}</td><td>${part}</td><td class="${cls}">${status}</td></tr>`;}).join('');
    return `<div class="receipt-head"><div class="receipt-mark">✓</div><div><span>IES Álvaro Falomir · Programación · Curso 2026/27</span><h2 id="receiptTitle">Justificante de validación · Java</h2></div></div><div class="receipt-grid"><div><span>Nombre y apellidos</span><strong>${escapeHtml(r.name)}</strong></div><div><span>Actividad</span><strong>Introducción a Java · Sentencias simples</strong></div><div><span>Ejercicios superados</span><strong>${r.done} / ${r.entries.length}</strong></div><div><span>Criterios comprobados</span><strong>${r.passed} / ${r.total}</strong></div><div><span>Fecha y hora local</span><strong>${escapeHtml(date)}</strong></div><div><span>Estado global</span><strong>${r.done===r.entries.length?'Todos los ejercicios validados':'Validación parcial / pendiente'}</strong></div><div class="wide"><span>Identificador local del informe (sin registro en servidor)</span><strong class="receipt-code">${code}</strong></div></div><h3>Detalle por ejercicio</h3><table class="receipt-table"><thead><tr><th>N.º</th><th>Ejercicio</th><th>Criterios</th><th>Estado</th></tr></thead><tbody>${rows}</tbody></table><p class="receipt-note">Autovalidación formativa del texto del código; este sitio no compila ni ejecuta Java y no verifica la identidad del alumno. Un criterio marcado refleja únicamente patrones detectados, no una garantía de corrección funcional. Este documento se genera en el navegador, no es una firma digital ni una certificación oficial y no sustituye la entrega en Aules. Conserva y entrega el código fuente conforme a las instrucciones del profesorado.</p><p class="receipt-note">Material docente: Rubén Pérez Ibáñez · IES Álvaro Falomir.</p>`;
  }
  function generateReceipt(){state.name=$('#studentName').value.trim();if(!state.name){$('#studentName').focus();alert('Introduce tu nombre y apellidos para generar el justificante.');return;}const r=snapshot();if(!r.entries.some(x=>x.code.trim())){alert('Todavía no hay código guardado: completa al menos un ejercicio para generar un justificante parcial.');return;}lastReceipt=r;$('#receiptDocument').innerHTML=receiptMarkup(r);$('#receiptModal').hidden=false;document.body.style.overflow='hidden';save();}
  function closeReceipt(){$('#receiptModal').hidden=true;document.body.style.overflow='';}
  $('#receiptBtn').addEventListener('click',generateReceipt);
  for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',closeReceipt);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#receiptModal').hidden)closeReceipt();});
  $('#printBtn').addEventListener('click',()=>window.print());
  function download(filename,body,type){const blob=new Blob([body],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  function safeFilename(str){return str.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').slice(0,65).replace(/^_|_$/g,'').toLowerCase()||'alumno';}
  $('#downloadBtn').addEventListener('click',()=>{if(!lastReceipt)return;const css=`@page{size:A4;margin:15mm}body{font:14px Arial,sans-serif;color:#1b293d;margin:35px auto;max-width:790px;padding:15px}.receipt-head{display:flex;gap:14px;border-bottom:2px solid #243d5b;padding-bottom:18px}.receipt-mark{font-size:30px;color:#167859}.receipt-head span,.receipt-grid span{display:block;color:#758298;font-size:11px}.receipt-head h2{margin:6px 0;font-size:24px}.receipt-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}.receipt-grid div{border:1px solid #e1e7ef;padding:11px;border-radius:6px}.receipt-grid .wide{grid-column:1/-1}.receipt-grid strong{display:block;font-size:13px;margin-top:4px;overflow-wrap:anywhere}h3{margin-top:24px}table{border-collapse:collapse;width:100%;font-size:11px}td,th{text-align:left;border-bottom:1px solid #dfe6ed;padding:8px}.done{color:#18754f}.partial{color:#967216}.pending{color:#8d9298}.receipt-note{color:#68788e;font-size:10px;line-height:1.5}.receipt-code{font-family:monospace}@media print{body{margin:0;max-width:none;padding:0}tr{break-inside:avoid}}`;const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Justificante Java · ${escapeHtml(lastReceipt.name)}</title><style>${css}</style></head><body>${receiptMarkup(lastReceipt)}</body></html>`;download(`justificante_java_${safeFilename(lastReceipt.name)}.html`,html,'text/html;charset=utf-8');});
  $('#exportBtn').addEventListener('click',()=>{const r=snapshot();if(!r.name){alert('Escribe tu nombre y apellidos antes de exportar.');$('#studentName').focus();return;}const record={actividad:'Introducción a Java · Sentencias simples',autor:'Rubén Pérez Ibáñez',alumno:r.name,fecha:r.when.toISOString(),aviso:'Registro local autodeclarado. Validaciones estáticas orientativas, no compilación ni ejecución.',ejercicios:r.entries.map(x=>({numero:x.id,titulo:x.title,codigo_java:x.code,validacion:x.validation}))};download(`ejercicios_java_${safeFilename(r.name)}.json`,JSON.stringify(record,null,2),'application/json;charset=utf-8');});
  select(Number(state.selected)>0&&Number(state.selected)<=exercises.length?Number(state.selected):1);
})();
